language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: "bf2965cc-cb9c-4a81-b44d-0c024eb8d012"
  app: thawing-dusk-24038