language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: h7Ii7iHumMk6THd+tK/zNhnmNl4gd5iPjmsgpejG9RTb7xNL+mTDfIZxUohccWS5gHoA+tCwpf0qvaa2LWl4obMzqBnliK+0U7qs+cd1yNvoaQk/i8OA+9lO8jTUR34GudXeadZ/L2s+OLtz//cI5FmwpqWEG3aIt8CroBLSFCC15YvRoKSN721yjHZzvkrPubP1qceQ3Nl4eV9tlq7KQQ+ovBHoJLkFGWDETQWyMaiVB9WlLZ+SE0fhRNHXU/+dVS8pq/QBywh+0ke/p066iCUdwCqFcqj01N0VimUK4s6qRLZHJ9ej0jW4T0/Woio4OtmgHpIkGPxWUp1nHqkYr1NE0+qNSmIiH1DElONBIjmZtP+xUlvyy5YExwUgeHUnu7SAcPp4MGaocoqmIBYx9K2SpeDLmGpZGDdUNCQGWj+wBGYoHAPdpOut3a+V9SfSPYuqOqht2m062Qaz1TdkkOGcUuF2tsm5ldjj+QI/zLEbAWf1/ebAKDtF5vLNe/gy/+VlljNgzz2UVZiGkLdNkrLkZRoxx9Yvy7W5L/6jmeXRdOVAmknh3/QH7hPXc1YgMGNw8+IvIlmS1ZkuLiyIEVRd05ChxW9G+cfhRlwKfTFBtY+G4rdubIs2JlkKhzrLL5/5XgLGZkr6LOVIf80RLrwKzXbW1UKdd0F/QbQXW8k=
  app: thawing-dusk-24038
