language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: "83285b7e-cabd-41fc-b9fd-e7cac5de303a"
  app: thawing-dusk-24038